// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
