version: '3.7'

services:
  # OWS chat Api
  
  owsactionhouse:
    image: ${REGISTRY:-ows}/owsactionhouse:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWSActionHouse/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
     - OWSAPIPathConfig__InternalPublicApiURL=${InternalPublicApiURL}
     - OWSAPIPathConfig__InternalInstanceManagementApiURL=${InternalInstanceManagementApiURL}
     - OWSAPIPathConfig__InternalCharacterPersistenceApiURL=${InternalCharacterPersistenceApiURL}
    ports:
      - "44320:80"
      - "44321:443"
    depends_on:
      - database
      - messaging
      
  owschat:
    image: ${REGISTRY:-ows}/owschat:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWSChat/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
     - OWSAPIPathConfig__InternalPublicApiURL=${InternalPublicApiURL}
     - OWSAPIPathConfig__InternalInstanceManagementApiURL=${InternalInstanceManagementApiURL}
     - OWSAPIPathConfig__InternalCharacterPersistenceApiURL=${InternalCharacterPersistenceApiURL}
    ports:
      - "44304:80"
      - "44305:443"
    depends_on:
      - database
      - messaging
      
  owsparty:
    image: ${REGISTRY:-ows}/owsparty:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: owsparty/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
    ports:
      - "44306:80"
      - "44307:443"
    depends_on:
      - database
      - messaging
      
  owsguild:
    image: ${REGISTRY:-ows}/owsguild:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: owsguild/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
    ports:
      - "44308:80"
      - "44309:443"
    depends_on:
      - database
      - messaging
      
      