version: '3.7'

services:
  # OWS chat Api
  owschat:
    image: ${REGISTRY:-ows}/owschat:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWSChat/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
     - OWSAPIPathConfig__InternalPublicApiURL=${InternalPublicApiURL}
     - OWSAPIPathConfig__InternalInstanceManagementApiURL=${InternalInstanceManagementApiURL}
     - OWSAPIPathConfig__InternalCharacterPersistenceApiURL=${InternalCharacterPersistenceApiURL}
    ports:
      - "44304:80"
      - "44305:443"
    depends_on:
      - database
      - messaging
      
      